dist: bionic
language: python
python:
  - 3.6

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
  - python3 setup.py install
  - pip freeze

script:
  - pytest --verbose --flakes

deploy:
  provider: pypi
  user: "__token__"
  # password: set by TravisCI's environment variable PYPI_PASSWORD
  # ref: https://travis-ci.org/consideratio/discourse-sso-oidc-bridge/settings
  distributions: sdist bdist_wheel
  on:
    # Only deploy on tagged commits instead of the default of only doing it to
    # the master branch. A tag does not belong specifically to a branch, so
    # without this it would fail to deploy for tags.
    tags: true
